feat: initial contribution of reworked best practices
eclipse-dataspace-protocol-base/dsp_best_practices pull request #8
Opened 2024-12-11 18:08 UTC by arnoweiss

## What this PR changes/adds

This PR describes a set of specification activities that a DSP-based dataspace may have to execute to facilitate interoperable end-to-end data exchange. 

_Please be sure to take a look at the [contributing guidelines](../CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](../PR_ETIQUETTE.md)._

2024-12-12 11:15 UTC, juliapampus requested changes

2024-12-12 11:15 UTC, juliapampus commented on best.practices/security.considerations.md
> +the necessary information to grant access to such data. Initially, a `Dataset` is advertised in the `Catalog`. Consumers
Sounds like repetitive information. We don't need to explain the processes here. This applies also to the following lines... Perhaps it would be better to start directly with the content of the TransferRequest or Start message and get to the point.

2024-12-12 11:22 UTC, arnoweiss commented on best.practices/security.considerations.md
> +`Authorization` header for the request is specified as the appropriate location for the client to present proof. Its
I'll add "access token"

2024-12-13 11:13 UTC, arnoweiss commented
cc @jimmarino

2024-12-14 15:30 UTC, arnoweiss commented on best.practices/interoperability.md
> +The normative JSON schemas are very permissive. Adding `additionalProperties` is always allowed as long as they satisfy
These statements are relevant for all subsequent chapters. Prose that's not specific to the particularities of DSP I'd rather leave out.

2024-12-20 09:46 UTC, merged